# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Andrea Pferscher"

# A description of your site for meta tag, search engine results.
description: "Postdoctoral research fellow at the Department of Informatics, University of Oslo."

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://apferscher.github.io"

# Favicon
favicon: images/favicon.png

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Publications
    url: /publications/
  - text: Projects
    url: /projects/
  - text: Teaching
    url: /teaching/
  - text: Contact
    url: /contact/

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: "&copy; Andrea Pferscher, 2025. Theme by [JustGoodThemes](https://www.justgoodthemes.com)."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
